version: '3'
services:
  postgres-service:
    image: "postgres:11"
    ports: 
      - "3001:5432"
    expose:
      - "5432"
    volumes:
      - ${VOLUME_PATH}/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
  api-service:
    build: .
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - "postgres-service"
    environment:
      - NODE_ENV=production
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=postgres-service
      - POSTGRES_PORT=5432
      - API_PORT=3000
      - API_HOST=localhost
      - API_SECRET=${API_SECRET}
      - API_REQUEST_TIMEOUT=${API_REQUEST_TIMEOUT}